#!/usr/bin/python
import webapp.api.model

Articles = [
    "Welcome to this application",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi rutrum laoreet nisi, a imperdiet " +
    "erat tempus egestas. Cras non eros nunc, a tempus lectus. Curabitur nulla lorem, semper a lacinia " +
    "in, ullamcorper non mauris. Aliquam adipiscing faucibus arcu, iaculis viverra ante accumsan at. Donec " +
    "ligula justo, varius non malesuada nec, fermentum eu nulla. Fusce at neque erat, non hendrerit augue. " +
    "Curabitur ultrices elementum iaculis. Ut rutrum mollis tempor. Maecenas gravida, massa nec imperdiet " +
    "accumsan, eros risus egestas lacus, sed pretium diam arcu et leo. Vestibulum vestibulum erat sit amet " +
    "ante luctus eget interdum tellus ornare. Fusce blandit erat id elit sollicitudin sit amet volutpat " +
    "lacus consequat. Donec porta auctor ultrices."
    ]

if __name__ == '__main__':
    db = webapp.api.model.Database()
    db.open("sqlite:///webapp.db")
    session = db.new_session()

    for article_text in Articles:
        session.add(webapp.api.model.NewsArticle("A title", article_text, "Henrik Nilsson"))

    session.add(webapp.api.model.User("henrikn", "customer", "Henrik Nilsson", "123"))
    session.add(webapp.api.model.User("christinan", "customer", "Christina Nilsson", "123"))
    session.add(webapp.api.model.User("svenv", "customer", "Sven Vult", "123"))
    session.add(webapp.api.model.User("perg", "customer", "Per Gustafsson", "123"))

    session.commit()
