#!/usr/bin/python
import subprocess

def dep_result(name, result):
   if result:
      print("dependency: %s is installed." % name)
   else:
      print("dependency ERROR: %s is NOT installed." % name)

def dep_module_check(name):
   try:
      __import__(name)
      dep_result(name, True)
   except ImportError:
      dep_result(name, False)

def dep_tool_check(name):
   try:
      process = subprocess.Popen(name, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      process.communicate()
      dep_result(name, True)
   except OSError:
      dep_result(name, False)

if __name__ == '__main__':
   print("Testing project dependencies")
   dep_module_check("cherrypy")
   dep_module_check("formencode")
   dep_module_check("genshi")
   dep_module_check("sqlalchemy")
   dep_module_check("sqlite3")

   print("")
   print("Testing development tools")
   dep_module_check("coverage")
   dep_tool_check("pylint")
   dep_tool_check(["nosetests", "--help"])
   dep_tool_check("sphinx-build")
